-- Yorktown Town-Wide Rummage Sale import (Aug 28–29, 2026).
-- GENERATED by seed_yorktown_rummage.mjs — run in the Supabase SQL editor.
-- Idempotent: re-running skips everything that already exists.
-- Everything is owned by jasonwynkoop1@yahoo.com, so you can edit or delete any
-- stop — and manage the event — in the app like your own sales.

do $$
declare
  v_owner uuid;
  v_event uuid;
begin
  -- 1) Resolve the owning account.
  select id into v_owner from auth.users where email = 'jasonwynkoop1@yahoo.com';
  if v_owner is null then
    raise exception 'No auth user with email % — check OWNER_EMAIL in the generator', 'jasonwynkoop1@yahoo.com';
  end if;

  -- 2) Find-or-create the event.
  select id into v_event
  from public.sale_events
  where title = 'Yorktown Town-Wide Rummage Sale' and start_date = date '2026-08-28'
  limit 1;

  if v_event is null then
    insert into public.sale_events
      (organizer_id, title, description, start_date, end_date,
       latitude, longitude, radius_m)
    values
      (v_owner, 'Yorktown Town-Wide Rummage Sale', 'The whole town is selling at once! 45+ homes across Yorktown, Friday & Saturday 8am–4pm. Mapped by Trove from the community flyer — tap each stop for what they’re selling, and save your favorites to plan your rounds. Happy hunting!',
       date '2026-08-28', date '2026-08-29',
       40.18307054, -85.48179350444443, 4842)
    returning id into v_event;
  end if;

  -- 3) Stops. Dedup: skip when ANY sale already overlaps the weekend at the
  --    same normalized address (residents' own posts are never duplicated).
  create temp table _stops (
    title text, description text, address text,
    latitude double precision, longitude double precision,
    start_date date, end_date date, categories text[], pricing_notes text
  ) on commit drop;

  insert into _stops values
    ('Stationary bike, elliptical', 'Stationary bike, elliptical. Friday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8908 W. Mill Rd., Yorktown, IN', 40.1711888, -85.4902311, date '2026-08-28', date '2026-08-28', array['sports']::text[], null),
    ('Quality name-brand items, home decor', 'Quality name-brand items, home decor. Friday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '2310 S. Broadway St., Yorktown, IN', 40.1725753, -85.4931794, date '2026-08-28', date '2026-08-28', array['clothing', 'other']::text[], null),
    ('Adult clothing, household items', 'Adult clothing, household items. Friday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8800 Greenville Dr., Yorktown, IN', 40.192403, -85.489125, date '2026-08-28', date '2026-08-28', array['clothing', 'other']::text[], null),
    ('Variety of items, indoor/outdoor household items', 'Variety of items, indoor/outdoor household items. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1103 S. Cummings Dr., Yorktown, IN', 40.183729, -85.460598, date '2026-08-29', date '2026-08-29', array['other']::text[], null),
    ('Antique glassware, pottery, vintage items', 'Antique glassware, pottery, vintage items. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '2409 S. Walnut St., Yorktown, IN', 40.1712863, -85.4940782, date '2026-08-29', date '2026-08-29', array['antiques']::text[], null),
    ('Kids clothes, ladies clothing, fall and home decor', 'Kids clothes, ladies clothing, fall and home decor. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '6210 W. Gray St., Muncie, IN', 40.1842248, -85.4577435, date '2026-08-29', date '2026-08-29', array['clothing']::text[], null),
    ('Boy''s clothes size 12-14, signs, antiques, misc.', 'Boy''s clothes size 12-14, signs, antiques, misc.. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '6213 W. Gray St., Muncie, IN', 40.1840529, -85.4577213, date '2026-08-29', date '2026-08-29', array['clothing', 'antiques']::text[], null),
    ('Household items, toddler & plus-size clothing', 'Household items, toddler & plus-size clothing. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '2813 S. Broadway St., Yorktown, IN', 40.1682229, -85.4907864, date '2026-08-29', date '2026-08-29', array['clothing', 'other']::text[], null),
    ('Household items, vintage stuff, antiques', 'Household items, vintage stuff, antiques. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '2000 S. York Rd., Yorktown, IN', 40.176142, -85.485712, date '2026-08-29', date '2026-08-29', array['antiques', 'other']::text[], null),
    ('Household items, PartyLite, decor, kitchen', 'Household items, PartyLite, decor, kitchen. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1805 N. Magnolia Dr., Muncie, IN', 40.208208, -85.487917, date '2026-08-29', date '2026-08-29', array['kitchen', 'other']::text[], null),
    ('Baby clothes/toys, tools, men''s/women''s clothing', 'Baby clothes/toys, tools, men''s/women''s clothing. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1280 S. Hoffer Dr., Muncie, IN', 40.1823948, -85.4576967, date '2026-08-29', date '2026-08-29', array['toys', 'tools', 'clothing']::text[], null),
    ('Adult/kids clothes, shoes, toys, household items', 'Adult/kids clothes, shoes, toys, household items. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8305 W. Weatherstone Ln., Yorktown, IN', 40.1877673, -85.4827367, date '2026-08-29', date '2026-08-29', array['clothing', 'toys']::text[], null),
    ('Women''s clothes, household, Christmas, misc.', 'Women''s clothes, household, Christmas, misc.. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '2210 S. Marsh Rd., Yorktown, IN', 40.171742, -85.499683, date '2026-08-29', date '2026-08-29', array['clothing', 'other']::text[], null),
    ('Clothes, shoes, Christmas, bedding & linens', 'Clothes, shoes, Christmas, bedding & linens. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '10000 W. Jackson St., Yorktown, IN', 40.2146567, -85.5034972, date '2026-08-29', date '2026-08-29', array['clothing', 'other']::text[], null),
    ('Lemonade/baked goods, desk, hutch, clothes', 'Lemonade/baked goods, desk, hutch, clothes. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '509 S. Buckingham Rd., Yorktown, IN', 40.1887563, -85.4898063, date '2026-08-29', date '2026-08-29', array['furniture', 'clothing']::text[], null),
    ('Household and Christmas items', 'Household and Christmas items. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '205 N. Eucalyptus Ct., Yorktown, IN', 40.1939867, -85.4825892, date '2026-08-29', date '2026-08-29', array['other']::text[], null),
    ('Loveseat, dresser, kid''s/adults'' clothes, decor', 'Loveseat, dresser, kid''s/adults'' clothes, decor. Saturday only, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '2320 S. Daugherty Ln., Yorktown, IN', 40.172351, -85.502879, date '2026-08-29', date '2026-08-29', array['furniture', 'clothing']::text[], null),
    ('Home decor, clothes, shoes', 'Home decor, clothes, shoes. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1609 S. Oakdale Dr., Yorktown, IN', 40.1791817, -85.4840837, date '2026-08-28', date '2026-08-29', array['clothing', 'other']::text[], null),
    ('Stockpile, laundry detergent, kid''s clothes, household', 'Stockpile, laundry detergent, kid''s clothes, household. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8004 W. Lindberg Dr., Yorktown, IN', 40.179436, -85.47947, date '2026-08-28', date '2026-08-29', array['clothing', 'other']::text[], null),
    ('Kids clothing/toys, teen boy/girl clothes', 'Kids clothing/toys, teen boy/girl clothes. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '9313 W. Smith St., Yorktown, IN', 40.1728482, -85.4962444, date '2026-08-28', date '2026-08-29', array['clothing', 'toys']::text[], null),
    ('New/antique furniture, clothes, electronics, tools', 'New/antique furniture, clothes, electronics, tools. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '312 S. Buckingham Rd., Yorktown, IN', 40.1908448, -85.4896107, date '2026-08-28', date '2026-08-29', array['furniture', 'electronics', 'tools']::text[], null),
    ('Little bit of everything', 'Little bit of everything. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '2905 S. Broadway St., Yorktown, IN', 40.1673474, -85.4903626, date '2026-08-28', date '2026-08-29', array['other']::text[], null),
    ('Toys, mugs, kitchen', 'Toys, mugs, kitchen. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8405 W. Red Bud Ln., Yorktown, IN', 40.1934268, -85.4843156, date '2026-08-28', date '2026-08-29', array['toys', 'kitchen']::text[], 'Everything is $1 or under'),
    ('TV stand, women''s clothes, bike, blankets, decor', 'TV stand, women''s clothes, bike, blankets, decor. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8806 W. Lone Beech Dr., Yorktown, IN', 40.1970546, -85.4891338, date '2026-08-28', date '2026-08-29', array['furniture', 'clothing', 'sports']::text[], null),
    ('Men''s bike, sports cards, tools, magazines', 'Men''s bike, sports cards, tools, magazines. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1217 S. Sarasota Dr., Yorktown, IN', 40.1821878, -85.4650482, date '2026-08-28', date '2026-08-29', array['sports', 'tools']::text[], null),
    ('Collectible vintage, vintage glassware, art/craft', 'Collectible vintage, vintage glassware, art/craft. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '9501 W. High St., Yorktown, IN', 40.171357, -85.497947, date '2026-08-28', date '2026-08-29', array['antiques']::text[], null),
    ('Tools, jewelry, electronics, toys, furniture, misc.', 'Tools, jewelry, electronics, toys, furniture, misc.. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '408 S. Prestwick Ln., Yorktown, IN', 40.1899236, -85.4724368, date '2026-08-28', date '2026-08-29', array['tools', 'electronics', 'toys', 'furniture']::text[], null),
    ('Name-brand clothes, home decor, furniture, misc.', 'Name-brand clothes, home decor, furniture, misc.. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1209 N. Snowmass Ln., Yorktown, IN', 40.2030146, -85.4492616, date '2026-08-28', date '2026-08-29', array['clothing', 'furniture']::text[], null),
    ('Vintage hats/clothes and shoes, electronics, misc.', 'Vintage hats/clothes and shoes, electronics, misc.. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '2208 N. Old Towne Ln., Yorktown, IN', 40.2120357, -85.44577, date '2026-08-28', date '2026-08-29', array['clothing', 'electronics', 'antiques']::text[], null),
    ('Housewares, toys, men''s/women''s clothes, misc.', 'Housewares, toys, men''s/women''s clothes, misc.. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1805 S. York Rd., Yorktown, IN', 40.1776272, -85.4859376, date '2026-08-28', date '2026-08-29', array['kitchen', 'toys', 'clothing']::text[], null),
    ('New bedding, home decor, housewares', 'New bedding, home decor, housewares. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '500 S. Riviera Ln., Yorktown, IN', 40.1890367, -85.4710584, date '2026-08-28', date '2026-08-29', array['other']::text[], null),
    ('Vintage/non-vintage household collectibles', 'Vintage/non-vintage household collectibles. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '9101 W. Arch St., Yorktown, IN', 40.171716, -85.493052, date '2026-08-28', date '2026-08-29', array['antiques']::text[], null),
    ('Clothing multi-size, toys, Squishmallows, decor', 'Clothing multi-size, toys, Squishmallows, decor. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '10137 W. Lexington Blvd., Yorktown, IN', 40.172821, -85.504909, date '2026-08-28', date '2026-08-29', array['clothing', 'toys']::text[], null),
    ('Vintage Apple monitor, video games, toys', 'Vintage Apple monitor, video games, toys. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8201 W. Weller St., Yorktown, IN', 40.1736523, -85.4819366, date '2026-08-28', date '2026-08-29', array['electronics', 'toys']::text[], null),
    ('Mowers, jewelry, furniture, VS tote bags, knives', 'Mowers, jewelry, furniture, VS tote bags, knives. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1214 S. Sarasota Dr., Yorktown, IN', 40.1833238, -85.4649408, date '2026-08-28', date '2026-08-29', array['tools', 'furniture']::text[], null),
    ('Baby girl items, women''s clothes, misc. items', 'Baby girl items, women''s clothes, misc. items. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8209 Fairview Dr., Yorktown, IN', 40.1758394, -85.4822901, date '2026-08-28', date '2026-08-29', array['clothing', 'toys']::text[], null),
    ('Rare antiques, plus-size Torrid, Lane Bryant', 'Rare antiques, plus-size Torrid, Lane Bryant. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1432 S. Colony Dr., Yorktown, IN', 40.1800488, -85.4839962, date '2026-08-28', date '2026-08-29', array['antiques', 'clothing']::text[], null),
    ('Designer clothes, coats, shirts, purses and more', 'Designer clothes, coats, shirts, purses and more. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8204 W. Pleasant Rd., Yorktown, IN', 40.177095, -85.4821037, date '2026-08-28', date '2026-08-29', array['clothing']::text[], null),
    ('Antique items, men''s 3X, women''s 2X clothes', 'Antique items, men''s 3X, women''s 2X clothes. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '309 N. Bliss Ave., Yorktown, IN', 40.19479, -85.486521, date '2026-08-28', date '2026-08-29', array['antiques', 'clothing']::text[], null),
    ('Furniture, tools, ladder', 'Furniture, tools, ladder. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '401 N. Aspen Ln., Yorktown, IN', 40.1960265, -85.4912636, date '2026-08-28', date '2026-08-29', array['furniture', 'tools']::text[], 'No prices — make an offer'),
    ('Various size clothes, household items, misc.', 'Various size clothes, household items, misc.. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '9900 W. Gallagher Way, Yorktown, IN', 40.1877802, -85.5019411, date '2026-08-28', date '2026-08-29', array['clothing', 'other']::text[], null),
    ('3-family sale: household, maternity, tools, kitchen', '3-family sale: household, maternity, tools, kitchen. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '6061 W. Cornbread Rd., Muncie, IN', 40.1710705, -85.4563537, date '2026-08-28', date '2026-08-29', array['tools', 'kitchen', 'clothing']::text[], null),
    ('Furniture, kid''s/adult clothes, home decor, walker', 'Furniture, kid''s/adult clothes, home decor, walker. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '7829 W. Frankie Ln., Yorktown, IN', 40.165981, -85.477068, date '2026-08-28', date '2026-08-29', array['furniture', 'clothing']::text[], null),
    ('Cookbooks, purses, crochet magazines', 'Cookbooks, purses, crochet magazines. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '1101 S. Sunset Dr., Yorktown, IN', 40.1843049, -85.4632515, date '2026-08-28', date '2026-08-29', array['books']::text[], null),
    ('Vintage Indiana glass', 'Vintage Indiana glass. Friday & Saturday, 8am–4pm.

Part of the Yorktown Town-Wide Rummage Sale (Aug 28–29). Posted by Trove from the community flyer — we’re not the seller, so messaging is off. Just come by during sale hours!', '8420 W. Adeline St., Yorktown, IN', 40.174715, -85.48442, date '2026-08-28', date '2026-08-29', array['antiques']::text[], null);

  insert into public.sales
    (user_id, title, description, address, latitude, longitude,
     start_date, end_date, start_time, end_time, status, categories,
     pricing_notes, allow_messages, event_id)
  select
    v_owner, s.title, s.description, s.address, s.latitude,
    s.longitude, s.start_date, s.end_date, time '08:00', time '16:00',
    'active', s.categories, s.pricing_notes, false, v_event
  from _stops s
  where not exists (
    select 1 from public.sales x
    where x.end_date >= date '2026-08-28'
      and x.start_date <= date '2026-08-29'
      and regexp_replace(lower(x.address), '[^a-z0-9]', '', 'g')
          like regexp_replace(lower(split_part(s.address, ',', 1)), '[^a-z0-9]', '', 'g') || '%'
  );
end $$;

-- 4) Summary: the event share link + how many stops are on it.
select
  e.title,
  'https://trove.sale/event/' || e.share_slug as share_link,
  (select count(*) from public.sales where event_id = e.id) as stops_on_event
from public.sale_events e
where e.title = 'Yorktown Town-Wide Rummage Sale' and e.start_date = date '2026-08-28';

-- ── Cleanup (run AFTER the weekend, optional) ────────────────────────────
-- Scoped to THIS EVENT only — never touches your other sales. You can also
-- just delete stops or the event from the app, since you own them.
-- delete from public.sales
--   where event_id in (select id from public.sale_events
--     where title = 'Yorktown Town-Wide Rummage Sale' and start_date = date '2026-08-28');
-- delete from public.sale_events
--   where title = 'Yorktown Town-Wide Rummage Sale' and start_date = date '2026-08-28';
