-- Structured offers (spec: docs/superpowers/specs/2026-08-30-messaging-offers-design.md)
--
-- Offers are a KIND of message, not a separate table: the existing realtime
-- subscription, the notify-new-message trigger, and thread ordering all work
-- unchanged. Mutation goes through definer RPCs because messages deliberately
-- has no UPDATE policy (20260524120000_messaging.sql:112-113) and because RLS
-- cannot restrict WHICH columns an update touches -- a seller-scoped UPDATE
-- policy would also let a seller rewrite the buyer's message text.
--
-- Every offer/system row carries human-readable body text. Three consumers
-- require it: messages_body_or_image_check, notify-new-message (400s on a
-- body-less row), and useInbox's `body ?? '[photo]'` preview. So the check
-- constraint is deliberately NOT widened here.
--
-- Four objects below already exist in production and are re-created here:
-- check_message_rate_limit(), can_review(), and the "Users can write their own
-- reviews" / "Participants can send messages" INSERT policies. Every one of
-- their bodies/predicates was copied verbatim from the live database
-- (`pg_get_functiondef` and `pg_get_expr(polwithcheck, polrelid)`), NOT
-- reconstructed from memory, and only the minimal new conjuncts were added --
-- see task-3-report.md for the live text and a per-object diff.
--
-- The two policies are the load-bearing half of this migration. can_review() is
-- a UI hint only, and the messages INSERT policy is what stops a client from
-- forging offer/system rows without going through the RPCs.

alter table public.messages
  add column if not exists kind text not null default 'text',
  add column if not exists offer_amount numeric(10,2),
  add column if not exists offer_status text,
  -- ON DELETE CASCADE, not SET NULL: messages_recipient_ck below requires
  -- recipient_id to be non-null exactly when kind = 'system', so a SET NULL
  -- action could never legally fire -- deleting a profile would issue
  -- `UPDATE messages SET recipient_id = NULL` on its system rows, violate the
  -- CHECK, and abort the delete. delete_my_account() routes through exactly
  -- that path (profiles -> auth.users is ON DELETE CASCADE), so the two would
  -- have deadlocked account deletion, masked only by RI trigger firing order.
  -- Cascade matches messages_sender_id_fkey and every other FK to profiles in
  -- this schema.
  add column if not exists recipient_id uuid references public.profiles(id) on delete cascade;

alter table public.messages drop constraint if exists messages_kind_ck;
alter table public.messages
  add constraint messages_kind_ck check (kind in ('text', 'offer', 'system'));

alter table public.messages drop constraint if exists messages_offer_fields_ck;
alter table public.messages
  add constraint messages_offer_fields_ck check (
    (kind = 'offer' and offer_amount is not null and offer_status is not null)
    or (kind <> 'offer' and offer_amount is null and offer_status is null)
  );

alter table public.messages drop constraint if exists messages_offer_status_ck;
alter table public.messages
  add constraint messages_offer_status_ck check (
    offer_status is null
    or offer_status in ('pending', 'accepted', 'declined', 'countered')
  );

-- Spec: recipient_id is non-null iff kind = 'system'. It names the party the
-- system row is *for* -- the participant who did NOT perform the action that
-- generated it -- which is meaningless on a human-authored row and required on
-- a generated one. Existing production rows are all kind='text' with a NULL
-- recipient_id (the column is new), so this validates without a backfill.
alter table public.messages drop constraint if exists messages_recipient_ck;
alter table public.messages
  add constraint messages_recipient_ck check (
    (kind = 'system' and recipient_id is not null)
    or (kind <> 'system' and recipient_id is null)
  );

create index if not exists messages_pending_offers_idx
  on public.messages (conversation_id)
  where kind = 'offer' and offer_status = 'pending';

-- Rate limit: only 'system' rows are exempt. They are generated by the RPCs
-- below, not typed by a human, so counting them would let an accepted offer eat
-- the seller's 20/minute budget. The early return matters as much as the filter:
-- the trigger is BEFORE INSERT, so a seller who had just sent 20 messages would
-- otherwise trip P0001 on the system row and abort the entire acceptance
-- transaction -- rolling back the offer_status flip and the listing hold.
--
-- Offers ('offer') ARE counted and ARE limited, by the same rationale in
-- reverse: a human taps Send on each one, so an unlimited offer channel would be
-- an un-throttled way to spam a seller.
--
-- Body below is the live definition from 20260524120000_messaging.sql, unchanged
-- since creation (confirmed via pg_get_functiondef): plpgsql, NOT security
-- definer, variable named v_recent_count, original error copy. Only the early
-- return and the `kind in (...)` line are new.
create or replace function public.check_message_rate_limit()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_recent_count int;
begin
  if new.kind = 'system' then
    return new;
  end if;

  select count(*) into v_recent_count
  from public.messages
  where sender_id = new.sender_id
    and kind in ('text', 'offer')
    and created_at > now() - interval '1 minute';
  if v_recent_count >= 20 then
    raise exception 'Slow down -- you can send up to 20 messages per minute.'
      using errcode = 'P0001';
  end if;
  return new;
end;
$$;

-- Never called directly (only fired by before_message_insert_rate_limit); a
-- session firing its own trigger via INSERT does not need EXECUTE on the
-- function, so this is safe to lock all the way down.
revoke execute on function public.check_message_rate_limit() from public, anon, authenticated;

-- Review eligibility must count only human messages. Auto-generated system rows
-- would otherwise let two users unlock reviewing each other without a real
-- exchange -- the exact loophole 20260617180000_reviews_require_real_thread.sql
-- was written to close.
--
-- can_review() is ONLY a UI hint: useReviews.ts calls it to decide whether to
-- show the review affordance, but submitReview() inserts into public.reviews
-- directly. Enforcement therefore lives in the "Users can write their own
-- reviews" INSERT policy, which duplicates this same gate inline -- so the
-- filter below is not sufficient on its own and the policy is re-created
-- immediately after this function.
--
-- Body below is the live definition from 20260617180000_reviews_require_real_thread.sql
-- (param name p_subject, sql/stable, returns TABLE(eligible, already_reviewed),
-- not security definer), confirmed via pg_get_functiondef. Only the two
-- `and m.kind = 'text'` / `and m2.kind = 'text'` lines are new. The param name
-- and two-column table return are load-bearing: src/hooks/useReviews.ts calls
-- `supabase.rpc('can_review', { p_subject: ... })` (named-arg RPC call -- a
-- renamed param breaks it) and destructures `row.eligible` / `row.already_reviewed`
-- from the result.
create or replace function public.can_review(p_subject uuid)
returns table (eligible boolean, already_reviewed boolean)
language sql stable
set search_path = public, pg_temp
as $$
  select
    (
      exists (
        select 1
        from public.conversations c
        where (
          (c.buyer_id = auth.uid() and c.seller_id = p_subject)
          or (c.seller_id = auth.uid() and c.buyer_id = p_subject)
        )
        and (
          select count(*) from public.messages m
          where m.conversation_id = c.id and m.sender_id = auth.uid()
            and m.kind = 'text'
        ) >= 2
        and exists (
          select 1 from public.messages m2
          where m2.conversation_id = c.id and m2.sender_id = p_subject
            and m2.kind = 'text'
        )
      )
    ) and auth.uid() is not null and auth.uid() <> p_subject,
    exists (
      select 1 from public.reviews r
      where r.subject_user_id = p_subject
        and r.author_user_id = auth.uid()
        and r.sale_id is null
    );
$$;

revoke execute on function public.can_review(uuid) from public, anon;
grant   execute on function public.can_review(uuid) to authenticated;

-- The real gate. This policy carries its own inline copy of the message-count
-- rule (it does not call can_review), so it needs the same `kind = 'text'`
-- filters or a pair of users could unlock reviews on each other purely by
-- trading offers and letting the RPCs emit system rows.
--
-- Predicate below is the live policy from 20260618170000_rls_initplan.sql:143-152
-- (confirmed byte-for-byte against pg_get_expr(polwithcheck, polrelid) on the
-- linked project), including its `(select auth.uid())` initplan wrapping and the
-- `sale_id is null` clause. The ONLY additions are `(m.kind = 'text')` and
-- `(m2.kind = 'text')`.
drop policy if exists "Users can write their own reviews" on public.reviews;
create policy "Users can write their own reviews" on public.reviews
  as permissive for insert to public
  with check ((((select auth.uid()) = author_user_id) AND (sale_id IS NULL) AND (EXISTS ( SELECT 1
   FROM conversations c
  WHERE ((((c.buyer_id = (select auth.uid())) AND (c.seller_id = reviews.subject_user_id)) OR ((c.seller_id = (select auth.uid())) AND (c.buyer_id = reviews.subject_user_id))) AND (( SELECT count(*) AS count
           FROM messages m
          WHERE ((m.conversation_id = c.id) AND (m.sender_id = (select auth.uid())) AND (m.kind = 'text'))) >= 2) AND (EXISTS ( SELECT 1
           FROM messages m2
          WHERE ((m2.conversation_id = c.id) AND (m2.sender_id = reviews.subject_user_id) AND (m2.kind = 'text')))))))));

-- Clients hold table-level INSERT on public.messages and the live INSERT policy
-- is column-blind, so a conversation participant could bypass send_offer
-- entirely: insert a fake `kind='offer'` row with offer_status='pending' on a
-- sold listing, or -- worse -- a forged `kind='system'` row reading "Offer
-- accepted -- $500" that renders with system chrome and fires the
-- notify-new-message push. That is a phishing surface, so end users are narrowed
-- to plain text and the offer columns are made unwritable from the client.
--
-- send_offer/respond_to_offer are unaffected: they are SECURITY DEFINER and, as
-- verified on the linked project, will be owned by `postgres` -- the same role
-- that owns public.messages -- which has relforcerowsecurity = false. A table
-- owner is exempt from RLS unless FORCE ROW LEVEL SECURITY is set, so the
-- definer bodies still write offer and system rows through this policy.
--
-- Predicate below is the live policy from 20260618170000_rls_initplan.sql:104-111
-- (confirmed byte-for-byte against pg_get_expr(polwithcheck, polrelid)),
-- including the blocked_users clause. The ONLY addition is the trailing
-- column-restriction conjunct.
drop policy if exists "Participants can send messages" on public.messages;
create policy "Participants can send messages" on public.messages
  as permissive for insert to public
  with check ((((select auth.uid()) = sender_id) AND (EXISTS ( SELECT 1
   FROM conversations c
  WHERE ((c.id = messages.conversation_id) AND ((c.buyer_id = (select auth.uid())) OR (c.seller_id = (select auth.uid()))) AND (NOT (EXISTS ( SELECT 1
           FROM blocked_users b
          WHERE (((b.blocker_id = c.buyer_id) AND (b.blocked_id = c.seller_id)) OR ((b.blocker_id = c.seller_id) AND (b.blocked_id = c.buyer_id))))))))) AND (kind = 'text') AND (offer_amount IS NULL) AND (offer_status IS NULL) AND (recipient_id IS NULL)));

-- Send (or counter) an offer. Crosses ownership: stamps the other party's
-- pending offer as countered, so it cannot be a plain INSERT policy.
create or replace function public.send_offer(
  p_conversation_id uuid,
  p_amount numeric
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid      uuid := (select auth.uid());
  v_amount   numeric;
  v_conv     record;
  v_listing  record;
  v_is_owner boolean;
  v_pending  uuid;
  v_body     text;
  v_id       uuid;
begin
  if v_uid is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;

  -- p_amount has unconstrained scale but offer_amount is numeric(10,2), so
  -- 0.004 would clear `> 0` here and then silently persist as $0.00. Round to
  -- the stored scale FIRST, then validate what will actually be written.
  v_amount := round(p_amount, 2);

  if v_amount is null or v_amount <= 0 or v_amount > 99999999 then
    raise exception 'invalid amount';
  end if;

  select id, buyer_id, seller_id, target_type, target_id
    into v_conv
  from public.conversations
  where id = p_conversation_id;

  if not found then
    raise exception 'conversation not found';
  end if;

  if v_uid <> v_conv.buyer_id and v_uid <> v_conv.seller_id then
    raise exception 'not a participant';
  end if;

  if v_conv.target_type <> 'listing' then
    raise exception 'offers are only supported on listings';
  end if;

  -- SECURITY DEFINER bypasses RLS, so the blocked_users predicate that the
  -- "Participants can send messages" INSERT policy would have enforced has to be
  -- replicated by hand. Predicate copied from that live policy.
  if exists (
    select 1 from public.blocked_users b
    where (b.blocker_id = v_conv.buyer_id and b.blocked_id = v_conv.seller_id)
       or (b.blocker_id = v_conv.seller_id and b.blocked_id = v_conv.buyer_id)
  ) then
    raise exception 'cannot send offers in a blocked conversation';
  end if;

  select id, user_id, title, status into v_listing
  from public.listings
  where id = v_conv.target_id;

  if not found then
    raise exception 'listing not found';
  end if;

  if v_listing.status = 'sold' then
    raise exception 'listing already sold';
  end if;

  v_is_owner := (v_listing.user_id = v_uid);

  -- Caller already has an offer awaiting a response.
  select id into v_pending
  from public.messages
  where conversation_id = p_conversation_id
    and kind = 'offer' and offer_status = 'pending' and sender_id = v_uid
  limit 1;

  if v_pending is not null then
    raise exception 'you already have a pending offer';
  end if;

  -- The other party's pending offer, if any. Looked up for BOTH senders, not
  -- just the owner: superseding it is what keeps one-pending-offer-per-
  -- conversation true (the intent behind messages_pending_offers_idx). When the
  -- stamp lived inside the owner-only branch, buyer offers -> seller counters
  -- (buyer's stamped countered) -> buyer offers again (allowed, they have no
  -- pending offer) left the seller's counter STILL pending, so two offers at
  -- two different prices were simultaneously acceptable.
  select id into v_pending
  from public.messages
  where conversation_id = p_conversation_id
    and kind = 'offer' and offer_status = 'pending' and sender_id <> v_uid
  limit 1;

  -- The owner may only COUNTER an existing offer, never open a negotiation
  -- against their own item. This rule stays owner-only; the stamping below
  -- does not.
  if v_is_owner and v_pending is null then
    raise exception 'nothing to counter';
  end if;

  if v_pending is not null then
    update public.messages set offer_status = 'countered' where id = v_pending;
  end if;

  -- listings.title has no DB length cap, and messages_body_or_image_check caps
  -- body at 2000 chars, so an untruncated title could make the composed body
  -- illegal and blow up the RPC on an otherwise valid offer.
  v_body := 'Offered $' || trim(to_char(v_amount, 'FM999999990.00'))
            || ' for ' || left(v_listing.title, 200);

  insert into public.messages
    (conversation_id, sender_id, body, kind, offer_amount, offer_status)
  values
    (p_conversation_id, v_uid, v_body, 'offer', v_amount, 'pending')
  returning id into v_id;

  return v_id;
end;
$$;

revoke execute on function public.send_offer(uuid, numeric) from public, anon;
grant   execute on function public.send_offer(uuid, numeric) to authenticated;

-- Accept or decline. The participant who did NOT send the offer responds -- so
-- the seller answers a buyer's offer, and the buyer answers a seller's counter.
-- Authorizing on listing ownership instead would have made a counter sendable
-- but unacceptable by anyone: its sender is the seller (blocked by the
-- self-response guard) and the buyer is not the owner. Accept also holds the
-- item; the hold table itself arrives in 20260830100100.
create or replace function public.respond_to_offer(
  p_offer_id uuid,
  p_action text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid       uuid := (select auth.uid());
  v_msg       record;
  v_conv      record;
  v_listing   record;
  v_responder uuid;
  v_buyer     uuid;
  v_recipient uuid;
  v_body      text;
begin
  if v_uid is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;

  if p_action not in ('accept', 'decline') then
    raise exception 'invalid action';
  end if;

  -- FOR UPDATE: the pending check below and the status flip further down are
  -- two separate statements, so without the row lock two concurrent accepts
  -- both read 'pending', both pass, and the item gets held twice (and the
  -- system row emitted twice). The lock serializes them -- the loser re-reads
  -- 'accepted' and raises 'offer is no longer pending'.
  select id, conversation_id, sender_id, offer_amount, offer_status, kind
    into v_msg
  from public.messages
  where id = p_offer_id
  for update;

  if not found or v_msg.kind <> 'offer' then
    raise exception 'offer not found';
  end if;

  -- Nobody responds to their own offer -- a seller must not be able to accept
  -- their own counter at a price the buyer never agreed to. Strictly this is
  -- implied by the responder check further down (which also excludes the
  -- sender), but it is kept: it fires before any lookup, it is the guard that
  -- has to hold if that derivation is ever edited, and it names the actual
  -- mistake instead of "not the responder". Checked before any mutation.
  if v_msg.sender_id = v_uid then
    raise exception 'cannot respond to your own offer';
  end if;

  if v_msg.offer_status <> 'pending' then
    raise exception 'offer is no longer pending';
  end if;

  select id, buyer_id, seller_id, target_type, target_id
    into v_conv
  from public.conversations where id = v_msg.conversation_id;

  -- `not found` leaves the record's fields NULL, and `NULL <> v_uid` is NULL,
  -- which IF treats as false -- so a missing row would SKIP the authorization
  -- checks below rather than fail them. Both lookups must assert found. This is
  -- not hypothetical: production already holds listing conversations whose
  -- target listing has been deleted.
  if not found then
    raise exception 'conversation not found';
  end if;

  if v_uid <> v_conv.buyer_id and v_uid <> v_conv.seller_id then
    raise exception 'not a participant';
  end if;

  if v_conv.target_type <> 'listing' then
    raise exception 'offers are only supported on listings';
  end if;

  -- SECURITY DEFINER bypasses RLS: replicate the blocked_users predicate from
  -- the "Participants can send messages" INSERT policy, which would otherwise
  -- have blocked the system row this function inserts.
  if exists (
    select 1 from public.blocked_users b
    where (b.blocker_id = v_conv.buyer_id and b.blocked_id = v_conv.seller_id)
       or (b.blocker_id = v_conv.seller_id and b.blocked_id = v_conv.buyer_id)
  ) then
    raise exception 'cannot respond to offers in a blocked conversation';
  end if;

  select id, user_id, title, status into v_listing
  from public.listings where id = v_conv.target_id;

  if not found then
    raise exception 'listing not found';
  end if;

  -- Authorization: the responder is the participant who did NOT send this
  -- offer. Owner-only was correct in exactly one direction. It handled a
  -- buyer's offer (sender = buyer, responder = seller = owner) and made a
  -- seller's COUNTER unacceptable by anyone -- its sender is the seller, so the
  -- self-response guard above stopped the seller and this check stopped the
  -- buyer, leaving an offer that could be sent and never answered.
  --
  -- The CASE is written to yield NULL rather than a participant if the offer's
  -- sender is somehow neither party, and the `is null` arm rejects that
  -- explicitly. Comparing against a bare NULL would have reproduced the same
  -- fall-through the `not found` guards above exist to prevent: `v_uid <> NULL`
  -- is NULL, and IF treats NULL as false, so the exception would be SKIPPED.
  -- Non-participants are already turned away by the participant check above;
  -- this narrows the two participants down to the one entitled to answer.
  v_responder := case
                   when v_msg.sender_id = v_conv.buyer_id  then v_conv.seller_id
                   when v_msg.sender_id = v_conv.seller_id then v_conv.buyer_id
                 end;

  if v_responder is null or v_responder <> v_uid then
    raise exception 'only the other party can respond to this offer';
  end if;

  -- Accepting writes listings.status, and this function is SECURITY DEFINER --
  -- so the owner-only UPDATE policy on listings does NOT apply here. Since a
  -- seller's counter is accepted by the BUYER, without this guard a non-owner
  -- could overwrite someone else's listing status at any later time: buyer
  -- offers -> seller sells elsewhere (status='sold') -> the offer is still
  -- pending -> accepting it resurrects the item as 'pending'. send_offer has
  -- the mirror-image check at send time; this is the check at respond time.
  --
  -- 'pending' is refused as well as 'sold': the item is already held for some
  -- buyer, and accepting a second offer would silently re-point that hold.
  -- DECLINE stays legal in every status, so a stale offer on a sold item can
  -- still be cleared. Checked before the offer_status update below, so a
  -- refused accept mutates nothing.
  if p_action = 'accept' and v_listing.status <> 'available' then
    raise exception 'listing is no longer available';
  end if;

  -- Two different people, and they stop coinciding the moment a seller's
  -- counter is in play, so neither may be read off v_msg.sender_id:
  --
  --   v_buyer     -- who the item is held FOR. Always the conversation's buyer.
  --                  On a buyer's offer that happens to be the offer's sender;
  --                  on a seller's counter it is v_uid, the accepter. Only
  --                  v_conv.buyer_id is right in both directions, and it is
  --                  what 20260830100100's listing_holds upsert consumes.
  --   v_recipient -- who the system notice is addressed to: the participant who
  --                  did not just act, i.e. never v_uid.
  v_buyer     := v_conv.buyer_id;
  v_recipient := case when v_uid = v_conv.buyer_id then v_conv.seller_id
                      else v_conv.buyer_id end;

  update public.messages
  set offer_status = case when p_action = 'accept' then 'accepted' else 'declined' end
  where id = p_offer_id;

  -- Both bodies are deliberately actor-free. The same row is generated whether
  -- the seller accepted a buyer's offer or the buyer accepted the seller's
  -- counter, and it is rendered to both parties, so any "you"/"the seller"
  -- phrasing would be false in one direction. State the amount and the
  -- resulting state; sender_id and recipient_id carry who did it and who it is
  -- for.
  if p_action = 'accept' then
    update public.listings set status = 'pending' where id = v_listing.id;
    v_body := 'Offer accepted -- $'
              || trim(to_char(v_msg.offer_amount, 'FM999999990.00'))
              || '. This item is on hold.';
  else
    v_body := 'Offer declined.';
  end if;

  insert into public.messages
    (conversation_id, sender_id, body, kind, recipient_id)
  values
    (v_msg.conversation_id, v_uid, v_body, 'system', v_recipient);
end;
$$;

revoke execute on function public.respond_to_offer(uuid, text) from public, anon;
grant   execute on function public.respond_to_offer(uuid, text) to authenticated;
