-- Structured offers (spec: docs/superpowers/specs/2026-08-30-messaging-offers-design.md)
--
-- Offers are a KIND of message, not a separate table: the existing realtime
-- subscription, the notify-new-message trigger, and thread ordering all work
-- unchanged. Mutation goes through definer RPCs because messages deliberately
-- has no UPDATE policy (20260524120000_messaging.sql:112-113) and because RLS
-- cannot restrict WHICH columns an update touches -- a seller-scoped UPDATE
-- policy would also let a seller rewrite the buyer's message text.
--
-- Every offer/system row carries human-readable body text. Three consumers
-- require it: messages_body_or_image_check, notify-new-message (400s on a
-- body-less row), and useInbox's `body ?? '[photo]'` preview. So the check
-- constraint is deliberately NOT widened here.
--
-- check_message_rate_limit() and can_review() below are CREATE OR REPLACE on
-- functions that already exist in production. Their bodies were copied from
-- `pg_get_functiondef` on the live database (not reconstructed from memory)
-- and only the minimal `kind = 'text'` filter was added to each -- see
-- task-3-report.md for the verbatim live definitions and a diff of the change.

alter table public.messages
  add column if not exists kind text not null default 'text',
  add column if not exists offer_amount numeric(10,2),
  add column if not exists offer_status text,
  add column if not exists recipient_id uuid references public.profiles(id) on delete set null;

alter table public.messages drop constraint if exists messages_kind_ck;
alter table public.messages
  add constraint messages_kind_ck check (kind in ('text', 'offer', 'system'));

alter table public.messages drop constraint if exists messages_offer_fields_ck;
alter table public.messages
  add constraint messages_offer_fields_ck check (
    (kind = 'offer' and offer_amount is not null and offer_status is not null)
    or (kind <> 'offer' and offer_amount is null and offer_status is null)
  );

alter table public.messages drop constraint if exists messages_offer_status_ck;
alter table public.messages
  add constraint messages_offer_status_ck check (
    offer_status is null
    or offer_status in ('pending', 'accepted', 'declined', 'countered')
  );

create index if not exists messages_pending_offers_idx
  on public.messages (conversation_id)
  where kind = 'offer' and offer_status = 'pending';

-- Rate limit: system rows are generated by RPCs, not typed by a human. Counting
-- them would let an accepted offer eat the sender's 20/minute budget and a burst
-- could abort the whole transaction (errcode P0001).
--
-- Body below is the live definition from 20260524120000_messaging.sql, unchanged
-- since creation (confirmed via pg_get_functiondef): plpgsql, NOT security
-- definer, variable named v_recent_count, original error copy. Only the
-- `and kind = 'text'` line is new.
create or replace function public.check_message_rate_limit()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_recent_count int;
begin
  select count(*) into v_recent_count
  from public.messages
  where sender_id = new.sender_id
    and kind = 'text'
    and created_at > now() - interval '1 minute';
  if v_recent_count >= 20 then
    raise exception 'Slow down -- you can send up to 20 messages per minute.'
      using errcode = 'P0001';
  end if;
  return new;
end;
$$;

-- Never called directly (only fired by before_message_insert_rate_limit); a
-- session firing its own trigger via INSERT does not need EXECUTE on the
-- function, so this is safe to lock all the way down.
revoke execute on function public.check_message_rate_limit() from public, anon, authenticated;

-- Review eligibility must count only human messages. Auto-generated system rows
-- would otherwise let two users unlock reviewing each other without a real
-- exchange -- the exact loophole 20260617180000_reviews_require_real_thread.sql
-- was written to close.
--
-- Body below is the live definition from 20260617180000_reviews_require_real_thread.sql
-- (param name p_subject, sql/stable, returns TABLE(eligible, already_reviewed),
-- not security definer), confirmed via pg_get_functiondef. Only the two
-- `and m.kind = 'text'` / `and m2.kind = 'text'` lines are new. The param name
-- and two-column table return are load-bearing: src/hooks/useReviews.ts calls
-- `supabase.rpc('can_review', { p_subject: ... })` (named-arg RPC call -- a
-- renamed param breaks it) and destructures `row.eligible` / `row.already_reviewed`
-- from the result.
create or replace function public.can_review(p_subject uuid)
returns table (eligible boolean, already_reviewed boolean)
language sql stable
set search_path = public, pg_temp
as $$
  select
    (
      exists (
        select 1
        from public.conversations c
        where (
          (c.buyer_id = auth.uid() and c.seller_id = p_subject)
          or (c.seller_id = auth.uid() and c.buyer_id = p_subject)
        )
        and (
          select count(*) from public.messages m
          where m.conversation_id = c.id and m.sender_id = auth.uid()
            and m.kind = 'text'
        ) >= 2
        and exists (
          select 1 from public.messages m2
          where m2.conversation_id = c.id and m2.sender_id = p_subject
            and m2.kind = 'text'
        )
      )
    ) and auth.uid() is not null and auth.uid() <> p_subject,
    exists (
      select 1 from public.reviews r
      where r.subject_user_id = p_subject
        and r.author_user_id = auth.uid()
        and r.sale_id is null
    );
$$;

revoke execute on function public.can_review(uuid) from public, anon;
grant   execute on function public.can_review(uuid) to authenticated;

-- Send (or counter) an offer. Crosses ownership: stamps the other party's
-- pending offer as countered, so it cannot be a plain INSERT policy.
create or replace function public.send_offer(
  p_conversation_id uuid,
  p_amount numeric
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid      uuid := (select auth.uid());
  v_conv     record;
  v_listing  record;
  v_is_owner boolean;
  v_pending  uuid;
  v_body     text;
  v_id       uuid;
begin
  if v_uid is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;

  if p_amount is null or p_amount <= 0 or p_amount > 99999999 then
    raise exception 'invalid amount';
  end if;

  select id, buyer_id, seller_id, target_type, target_id
    into v_conv
  from public.conversations
  where id = p_conversation_id;

  if not found then
    raise exception 'conversation not found';
  end if;

  if v_uid <> v_conv.buyer_id and v_uid <> v_conv.seller_id then
    raise exception 'not a participant';
  end if;

  if v_conv.target_type <> 'listing' then
    raise exception 'offers are only supported on listings';
  end if;

  select id, user_id, title, status into v_listing
  from public.listings
  where id = v_conv.target_id;

  if not found then
    raise exception 'listing not found';
  end if;

  if v_listing.status = 'sold' then
    raise exception 'listing already sold';
  end if;

  v_is_owner := (v_listing.user_id = v_uid);

  -- Caller already has an offer awaiting a response.
  select id into v_pending
  from public.messages
  where conversation_id = p_conversation_id
    and kind = 'offer' and offer_status = 'pending' and sender_id = v_uid
  limit 1;

  if v_pending is not null then
    raise exception 'you already have a pending offer';
  end if;

  if v_is_owner then
    -- The owner may only COUNTER an existing offer, never open a negotiation
    -- against their own item.
    select id into v_pending
    from public.messages
    where conversation_id = p_conversation_id
      and kind = 'offer' and offer_status = 'pending' and sender_id <> v_uid
    limit 1;

    if v_pending is null then
      raise exception 'nothing to counter';
    end if;

    update public.messages set offer_status = 'countered' where id = v_pending;
  end if;

  v_body := 'Offered $' || trim(to_char(p_amount, 'FM999999990.00'))
            || ' for ' || v_listing.title;

  insert into public.messages
    (conversation_id, sender_id, body, kind, offer_amount, offer_status)
  values
    (p_conversation_id, v_uid, v_body, 'offer', p_amount, 'pending')
  returning id into v_id;

  return v_id;
end;
$$;

revoke execute on function public.send_offer(uuid, numeric) from public, anon;
grant   execute on function public.send_offer(uuid, numeric) to authenticated;

-- Accept or decline. Only the listing owner may respond. Accept also holds the
-- item; the hold table itself arrives in 20260830100100.
create or replace function public.respond_to_offer(
  p_offer_id uuid,
  p_action text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid     uuid := (select auth.uid());
  v_msg     record;
  v_conv    record;
  v_listing record;
  v_buyer   uuid;
  v_body    text;
begin
  if v_uid is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;

  if p_action not in ('accept', 'decline') then
    raise exception 'invalid action';
  end if;

  select id, conversation_id, sender_id, offer_amount, offer_status, kind
    into v_msg
  from public.messages
  where id = p_offer_id;

  if not found or v_msg.kind <> 'offer' then
    raise exception 'offer not found';
  end if;

  if v_msg.offer_status <> 'pending' then
    raise exception 'offer is no longer pending';
  end if;

  select id, buyer_id, seller_id, target_type, target_id
    into v_conv
  from public.conversations where id = v_msg.conversation_id;

  select id, user_id, title into v_listing
  from public.listings where id = v_conv.target_id;

  if v_listing.user_id <> v_uid then
    raise exception 'only the listing owner can respond';
  end if;

  v_buyer := v_msg.sender_id;

  update public.messages
  set offer_status = case when p_action = 'accept' then 'accepted' else 'declined' end
  where id = p_offer_id;

  if p_action = 'accept' then
    update public.listings set status = 'pending' where id = v_listing.id;
    v_body := 'Offer accepted -- $'
              || trim(to_char(v_msg.offer_amount, 'FM999999990.00'))
              || '. This item is on hold.';
  else
    v_body := 'Offer declined.';
  end if;

  insert into public.messages
    (conversation_id, sender_id, body, kind, recipient_id)
  values
    (v_msg.conversation_id, v_uid, v_body, 'system', v_buyer);
end;
$$;

revoke execute on function public.respond_to_offer(uuid, text) from public, anon;
grant   execute on function public.respond_to_offer(uuid, text) to authenticated;
